### ISSUE TITLE
Typo in Start Menu

### ISSUE THREAD

**Issue by andrewjrhill** [padraigfl/packard-belle-desktop#1]
Figured I would point out a little typo I spotted this morning checking out your awesome project. `Suport` should be `Support`.

https://github.com/padraigfl/packard-belle-desktop/blob/a9abfab06bd79ab8cd379a0f495f25b707749dc3/src/contexts/programs.js#L54

**Comment by padraigfl** [comment]
Thanks Andrew, resolved it!

"Help" is so omnipresent over the Windows UI it's pretty crazy, easy to forget just how many people had never touched a computer before 95/98 I guess.
