### ISSUE TITLE
cant install dependencies

### ISSUE THREAD

**Issue by ondrej-oake** [padraigfl/packard-belle-desktop#41]
Hey guys would you mind to update this repo with the latest dependencies. 
I'm having really difficult times installing it
thanks

**Comment by padraigfl** [comment]
Hi, thanks for flagging this! Didn't realise it had gotten so old...

If you're still interested can you check out the branch `node-14` ( https://github.com/padraigfl/packard-belle-desktop/tree/node-14 ) and check if it works for you?  If it doesn't can you send on the error log you get?

Have done a fairly rough update to get it working with node 14 there, if it seems okay I'll go ahead and do a minor version bump and update this repo too; can follow that up with a more thorough modernisation of the build.

**Comment by padraigfl** [comment]
@ondrej-oake 

Hi, thanks for flagging this! Didn't realise it had gotten so old...

If you're still interested can you check out the branch `node-14` ( https://github.com/padraigfl/packard-belle-desktop/tree/node-14 ) and check if it works for you?  If it doesn't can you send on the error log you get?

Have done a fairly rough update to get it working with node 14 there, if it seems okay I'll go ahead and do a minor version bump and update this repo too; can follow that up with a more thorough modernisation of the build.

**Comment by padraigfl** [comment]
Should be resolved in https://github.com/padraigfl/packard-belle-desktop/pull/42
